version: '3.6'

services:
    springboot:
        build: .
        container_name: spring-boot-docker
        ports:
            - 8888:8888
        depends_on:
            - kafka
            - zookeeper
        networks:
            - network

    zookeeper:
        image: confluentinc/cp-zookeeper:5.2.1
        container_name: zookeeper
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
        ports:
            - 2181:2181
        networks:
            - network

    kafka:
        image: confluentinc/cp-kafka:5.2.1
        container_name: kafka
        restart: always
        ports:
            - 9092:9092
        expose:
            - 9092
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            ALLOW_PLAINTEXT_LISTENER: "yes"            
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
            KAFKA_CREATE_TOPICS: "TestTopic"
        networks:
            - network

networks: 
    network:
        driver: bridge