# docker build -t spring-boot-docker.jar .
# docker run -p 8888:8888 spring-boot-docker.jar

FROM openjdk:8
EXPOSE 8888
ADD target/spring-boot-docker.jar spring-boot-docker.jar
ENTRYPOINT ["java", "-jar", "/spring-boot-docker.jar"]